-- MySQL Script generated by MySQL Workbench
-- Sun Jun  2 02:33:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema barrioseguro
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS barrioseguro ;

-- -----------------------------------------------------
-- Schema barrioseguro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS barrioseguro DEFAULT CHARACTER SET utf8mb3 ;
USE barrioseguro ;

-- -----------------------------------------------------
-- Table barrioseguro.asociacion_vecinal
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS barrioseguro.asociacion_vecinal (
  id_asociacion CHAR(6) NOT NULL,
  nombre VARCHAR(180) NULL DEFAULT NULL,
  distrito VARCHAR(90) NULL DEFAULT NULL,
  provincia VARCHAR(90) NULL DEFAULT NULL,
  est_plus CHAR(2) NULL DEFAULT NULL,
  membresia INT NULL,
  asociacion_vecinalcol VARCHAR(45) NULL,
  PRIMARY KEY (id_asociacion))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table barrioseguro.encuesta
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS barrioseguro.encuesta (
  id_encuesta INT NOT NULL AUTO_INCREMENT,
  titulo VARCHAR(180) NULL DEFAULT NULL,
  opcion_ganadora VARCHAR(180) NULL DEFAULT NULL,
  votantes_total INT NULL DEFAULT NULL,
  id_asociacion CHAR(6) NULL DEFAULT NULL,
  PRIMARY KEY (id_encuesta),
  CONSTRAINT encuesta_ibfk_1
    FOREIGN KEY (id_asociacion)
    REFERENCES barrioseguro.asociacion_vecinal (id_asociacion))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX id_asociacion ON barrioseguro.encuesta (id_asociacion ASC) VISIBLE;


-- -----------------------------------------------------
-- Table barrioseguro.reunion
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS barrioseguro.reunion (
  id_reunion INT NOT NULL AUTO_INCREMENT,
  hora_reunion TIME NULL DEFAULT NULL,
  fecha_reunion DATE NULL DEFAULT NULL,
  asunto_reunion VARCHAR(180) NULL DEFAULT NULL,
  id_asociacion CHAR(6) NULL DEFAULT NULL,
  PRIMARY KEY (id_reunion),
  CONSTRAINT reunion_ibfk_1
    FOREIGN KEY (id_asociacion)
    REFERENCES barrioseguro.asociacion_vecinal (id_asociacion))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX id_asociacion ON barrioseguro.reunion (id_asociacion ASC) VISIBLE;


-- -----------------------------------------------------
-- Table barrioseguro.acuerdo
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS barrioseguro.acuerdo (
  id_acuerdo INT NOT NULL AUTO_INCREMENT,
  titulo VARCHAR(180) NULL DEFAULT NULL,
  descripcion VARCHAR(360) NULL DEFAULT NULL,
  id_reunion INT NOT NULL,
  id_encuesta INT NULL DEFAULT NULL,
  PRIMARY KEY (id_acuerdo),
  CONSTRAINT fk_acuerdo_encuesta1
    FOREIGN KEY (id_encuesta)
    REFERENCES barrioseguro.encuesta (id_encuesta),
  CONSTRAINT fk_acuerdo_reunion1
    FOREIGN KEY (id_reunion)
    REFERENCES barrioseguro.reunion (id_reunion))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX fk_acuerdo_reunion1_idx ON barrioseguro.acuerdo (id_reunion ASC) VISIBLE;

CREATE INDEX fk_acuerdo_encuesta1_idx ON barrioseguro.acuerdo (id_encuesta ASC) VISIBLE;


-- -----------------------------------------------------
-- Table barrioseguro.cargo
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS barrioseguro.cargo (
  id INT NOT NULL,
  nombre_cargo VARCHAR(45) NULL DEFAULT NULL,
  fecha_inicio DATE NULL DEFAULT NULL,
  fecha_fin DATE NULL DEFAULT NULL,
  cargo_dni_vecino CHAR(8) NOT NULL,
  sueldo INT NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table barrioseguro.vecino
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS barrioseguro.vecino (
  dni CHAR(8) NOT NULL,
  nombre VARCHAR(45) NULL DEFAULT NULL,
  apellido VARCHAR(45) NULL DEFAULT NULL,
  direccion VARCHAR(180) NULL DEFAULT NULL,
  genero VARCHAR(10) NULL DEFAULT NULL,
  clas_vecino VARCHAR(12) NULL DEFAULT NULL,
  contraseña VARCHAR(45) NULL,
  id_asociacion CHAR(6) NOT NULL,
  cargo_id INT NOT NULL,
  num_celular VARCHAR(45) NULL,
  correo VARCHAR(45) NULL,
  vecino_dni CHAR(8) NOT NULL,
  PRIMARY KEY (dni, vecino_dni),
  CONSTRAINT vecino_ibfk_1
    FOREIGN KEY (id_asociacion)
    REFERENCES barrioseguro.asociacion_vecinal (id_asociacion),
  CONSTRAINT fk_vecino_cargo1
    FOREIGN KEY (cargo_id)
    REFERENCES barrioseguro.cargo (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX id_asociacion ON barrioseguro.vecino (id_asociacion ASC) VISIBLE;

CREATE INDEX fk_vecino_cargo1_idx ON barrioseguro.vecino (cargo_id ASC) VISIBLE;


-- -----------------------------------------------------
-- Table barrioseguro.asistente_reu
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS barrioseguro.asistente_reu (
  reunion_id INT NOT NULL,
  vecino_dni CHAR(8) NOT NULL,
  PRIMARY KEY (reunion_id, vecino_dni),
  CONSTRAINT asistente_reu_ibfk_1
    FOREIGN KEY (reunion_id)
    REFERENCES barrioseguro.reunion (id_reunion),
  CONSTRAINT asistente_reu_ibfk_2
    FOREIGN KEY (vecino_dni)
    REFERENCES barrioseguro.vecino (dni))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX vecino_dni ON barrioseguro.asistente_reu (vecino_dni ASC) VISIBLE;


-- -----------------------------------------------------
-- Table barrioseguro.gasto
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS barrioseguro.gasto (
  id_gasto INT NOT NULL AUTO_INCREMENT,
  fecha_gasto DATE NULL DEFAULT NULL,
  titulo VARCHAR(180) NULL DEFAULT NULL,
  monto_gastado DOUBLE NULL DEFAULT NULL,
  id_asociacion CHAR(6) NULL DEFAULT NULL,
  PRIMARY KEY (id_gasto),
  CONSTRAINT gasto_ibfk_1
    FOREIGN KEY (id_asociacion)
    REFERENCES barrioseguro.asociacion_vecinal (id_asociacion))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX id_asociacion ON barrioseguro.gasto (id_asociacion ASC) VISIBLE;


-- -----------------------------------------------------
-- Table barrioseguro.pago
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS barrioseguro.pago (
  id_pago INT NOT NULL AUTO_INCREMENT,
  dni CHAR(8) NOT NULL,
  fecha_pago DATE NULL DEFAULT NULL,
  hora_pago TIME NULL DEFAULT NULL,
  monto_pago DOUBLE NULL DEFAULT NULL,
  metodo_pago VARCHAR(45) NULL DEFAULT NULL,
  cancelado TINYINT NULL,
  PRIMARY KEY (id_pago),
  CONSTRAINT pago_ibfk_1
    FOREIGN KEY (dni)
    REFERENCES barrioseguro.vecino (dni))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX dni ON barrioseguro.pago (dni ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;